spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: banyuan_route #路由到半圆官网
          uri: https://pre.banyuan.club
          predicates:
            - Query=url,banyuan

## 精确的路由的地址 要放在模糊的路由地址前面
        - id: product_route
          uri: lb://banyuanmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://banyuanmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}


        # 路由到具体地址的时候可能会出现 错误 这是因为我们访问的时候
# http://localhost:88/index?url=banyuan 百度或者半圆下面没有hello请求 报错404 (没关系)
        - id: admin_route
          uri: lb://renren-fast #lb 表示负载均衡到这个路径
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
# 以后的前端项目都要加上api前缀













