spring:
  datasource:
    username: root
    password: zhou
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.11.149:3306/banyuanmall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.149:8848
  application:
    name: banyuanmall-ware
#配置sql
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
server:
  port: 11000

# 如果出现了  endpoint  is  blank 错误 就添加如下配置
management:
  endpoint:
    shutdown:
      enabled: true